// <auto-generated />
using System;
using LvlUp.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LvlUp.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lvlup")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LvlUp.Domain.Hunters.Hunter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AssessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at_utc");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer")
                        .HasColumnName("charisma");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer")
                        .HasColumnName("current_xp");

                    b.Property<int>("DisplayNamePreference")
                        .HasColumnType("integer")
                        .HasColumnName("display_name_preference");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("GitHubUsername")
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("git_hub_username");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Looks")
                        .HasColumnType("integer")
                        .HasColumnName("looks");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Physique")
                        .HasColumnType("integer")
                        .HasColumnName("physique");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer")
                        .HasColumnName("stamina");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.Property<int>("WellBeing")
                        .HasColumnType("integer")
                        .HasColumnName("well_being");

                    b.HasKey("Id")
                        .HasName("pk_hunters");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_hunters_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_hunters_username");

                    b.ToTable("hunters", "lvlup");
                });

            modelBuilder.Entity("LvlUp.Domain.Quests.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<Guid>("HunterId")
                        .HasColumnType("uuid")
                        .HasColumnName("hunter_id");

                    b.Property<DateTime?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("Verification")
                        .HasColumnType("integer")
                        .HasColumnName("verification");

                    b.HasKey("Id")
                        .HasName("pk_quests");

                    b.HasIndex("HunterId")
                        .HasDatabaseName("ix_quests_hunter_id");

                    b.ToTable("quests", "lvlup");
                });

            modelBuilder.Entity("LvlUp.Domain.Quests.QuestCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("HunterId")
                        .HasColumnType("uuid")
                        .HasColumnName("hunter_id");

                    b.Property<string>("Note")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("note");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<int>("StatAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("stat_awarded");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id")
                        .HasName("pk_quest_completions");

                    b.HasIndex("HunterId")
                        .HasDatabaseName("ix_quest_completions_hunter_id");

                    b.ToTable("quest_completions", "lvlup");
                });

            modelBuilder.Entity("LvlUp.Domain.Quests.Quest", b =>
                {
                    b.HasOne("LvlUp.Domain.Hunters.Hunter", null)
                        .WithMany()
                        .HasForeignKey("HunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quests_hunters_hunter_id");
                });
#pragma warning restore 612, 618
        }
    }
}
